// =====================================================================
// BANCO DE DADOS DO JOGO
// Estrutura preservada de propósito para compatibilidade com app.js:
//   - mode1[tema] = [{ word, hint }]     -> dica em forma de palavra-chave
//   - mode2[tema] = [{ word, similar }]  -> palavra parecida p/ o impostor
// =====================================================================
const gameDatabase = {
    mode1: {
        "Internet e Cultura Pop": [
            { word: "Meme", hint: "Viral" },
            { word: "Live", hint: "Chat" },
            { word: "Podcast", hint: "Microfone" },
            { word: "Stories", hint: "24 Horas" },
            { word: "Unboxing", hint: "Caixa" },
            { word: "Cringe", hint: "Vergonha Alheia" },
            { word: "Hater", hint: "Comentário" },
            { word: "Clickbait", hint: "Título" },
            { word: "Deepfake", hint: "Falso" },
            { word: "Streaming", hint: "Buffering" },
            { word: "Trend", hint: "Desafio" },
            { word: "Reels", hint: "Musiquinha" }
        ],
        "Profissões do Futuro": [
            { word: "Influenciador Digital", hint: "Publi" },
            { word: "Streamer", hint: "Twitch" },
            { word: "Prompt Engineer", hint: "IA" },
            { word: "Social Media", hint: "Feed" },
            { word: "Growth Hacker", hint: "Métrica" },
            { word: "Analista de Dados", hint: "Dashboard" },
            { word: "DevOps", hint: "Deploy" },
            { word: "UX Writer", hint: "Microtexto" },
            { word: "Dropshipper", hint: "Estoque Zero" },
            { word: "Editor de Vídeo", hint: "Corte" },
            { word: "Gestor de Tráfego", hint: "Anúncio" },
            { word: "Copywriter", hint: "Persuasão" }
        ],
        "Festas e Tradições Brasileiras": [
            { word: "Carnaval", hint: "Bloco" },
            { word: "Festa Junina", hint: "Quadrilha" },
            { word: "Réveillon", hint: "Espumante" },
            { word: "Casamento", hint: "Aliança" },
            { word: "Formatura", hint: "Beca" },
            { word: "Churrasco", hint: "Espeto" },
            { word: "Chá de Bebê", hint: "Fralda" },
            { word: "Despedida de Solteiro", hint: "Cordão" },
            { word: "Show de Rock", hint: "Palco" },
            { word: "Aniversário Infantil", hint: "Palhaço" },
            { word: "Vaquejada", hint: "Laço" },
            { word: "Rodeio", hint: "Touro" }
        ],
        "Fenômenos e Espaço": [
            { word: "Eclipse", hint: "Sombra" },
            { word: "Buraco Negro", hint: "Gravidade" },
            { word: "Aurora Boreal", hint: "Polo" },
            { word: "Vulcão", hint: "Lava" },
            { word: "Terremoto", hint: "Tremor" },
            { word: "Maré", hint: "Lua" },
            { word: "Meteoro", hint: "Rastro" },
            { word: "Estação Espacial", hint: "Órbita" },
            { word: "Furacão", hint: "Vento" },
            { word: "Arco-Íris", hint: "Prisma" },
            { word: "Big Bang", hint: "Origem" },
            { word: "Nevasca", hint: "Frio" }
        ],
        "Vida Adulta e Burocracia": [
            { word: "Golpe do Pix", hint: "Urgente" },
            { word: "Boleto Vencido", hint: "Multa" },
            { word: "Fatura do Cartão", hint: "Limite" },
            { word: "Declaração de IR", hint: "Leão" },
            { word: "Fila do Banco", hint: "Senha" },
            { word: "Trânsito", hint: "Buzina" },
            { word: "Wi-Fi Caindo", hint: "Instável" },
            { word: "Reunião Desnecessária", hint: "E-mail" },
            { word: "Assinatura de Streaming", hint: "Cobrança" },
            { word: "Golpe do Falso Motoboy", hint: "Entrega" },
            { word: "Spam", hint: "Promoção" },
            { word: "Prazo Apertado", hint: "Deadline" }
        ],
        "Esportes Radicais": [
            { word: "Rapel", hint: "Corda" },
            { word: "Paraquedismo", hint: "Queda Livre" },
            { word: "Surfe", hint: "Onda" },
            { word: "Escalada", hint: "Rocha" },
            { word: "Bungee Jump", hint: "Elástico" },
            { word: "Parapente", hint: "Asa" },
            { word: "Skate Vertical", hint: "Rampa" },
            { word: "Trilha 4x4", hint: "Lama" },
            { word: "Kitesurf", hint: "Pipa" },
            { word: "Slackline", hint: "Equilíbrio" },
            { word: "Canyoning", hint: "Cachoeira" },
            { word: "Motocross", hint: "Salto" }
        ],
        "Mitologia e Ficção": [
            { word: "Vampiro", hint: "Presas" },
            { word: "Lobisomem", hint: "Lua Cheia" },
            { word: "Zumbi", hint: "Cérebro" },
            { word: "Sereia", hint: "Canto" },
            { word: "Bruxa", hint: "Caldeirão" },
            { word: "Minotauro", hint: "Labirinto" },
            { word: "Fênix", hint: "Renascer" },
            { word: "Górgona", hint: "Serpentes" },
            { word: "Duende", hint: "Travessura" },
            { word: "Golem", hint: "Argila" },
            { word: "Kraken", hint: "Tentáculo" },
            { word: "Valquíria", hint: "Guerreira" }
        ],
        "Curiosidades do Corpo e Mente": [
            { word: "Déjà Vu", hint: "Repetição" },
            { word: "Sonambulismo", hint: "Sono" },
            { word: "Soluço", hint: "Diafragma" },
            { word: "Alergia", hint: "Coceira" },
            { word: "Enjoo", hint: "Náusea" },
            { word: "Memória", hint: "Lembrança" },
            { word: "Instinto", hint: "Reflexo" },
            { word: "Adrenalina", hint: "Susto" },
            { word: "Sonho Lúcido", hint: "Consciência" },
            { word: "Amnésia", hint: "Esquecimento" },
            { word: "Hipnose", hint: "Transe" },
            { word: "Intuição", hint: "Sexto Sentido" }
        ]
    },
    mode2: {
        "Gastronomia Global": [
            { word: "Ramen", similar: "Yakisoba" },
            { word: "Taco", similar: "Burrito" },
            { word: "Croissant", similar: "Pão de Queijo" },
            { word: "Feijoada", similar: "Cozido" },
            { word: "Açaí na Tigela", similar: "Sorvete" },
            { word: "Churros", similar: "Bolinho de Chuva" },
            { word: "Fondue", similar: "Raclette" },
            { word: "Sushi", similar: "Sashimi" },
            { word: "Coxinha", similar: "Croquete" },
            { word: "Pastel", similar: "Empanada" },
            { word: "Panqueca Americana", similar: "Waffle" },
            { word: "Risoto", similar: "Paella" },
            { word: "Café Espresso", similar: "Café Coado" },
            { word: "Whisky", similar: "Bourbon" }
        ],
        "Apps e Redes Sociais": [
            { word: "Instagram", similar: "TikTok" },
            { word: "WhatsApp", similar: "Telegram" },
            { word: "Netflix", similar: "Prime Video" },
            { word: "Spotify", similar: "Deezer" },
            { word: "Uber", similar: "99" },
            { word: "iFood", similar: "Rappi" },
            { word: "PayPal", similar: "PicPay" },
            { word: "Zoom", similar: "Google Meet" },
            { word: "ChatGPT", similar: "Gemini" },
            { word: "Canva", similar: "Photoshop" },
            { word: "LinkedIn", similar: "Indeed" },
            { word: "Discord", similar: "Slack" }
        ],
        "Trabalho e Carreira": [
            { word: "Home Office", similar: "Coworking" },
            { word: "CLT", similar: "PJ" },
            { word: "Estágio", similar: "Trainee" },
            { word: "Freelancer", similar: "MEI" },
            { word: "Reunião", similar: "Call" },
            { word: "Chefe", similar: "Sócio" },
            { word: "Currículo", similar: "Portfólio" },
            { word: "Networking", similar: "Mentoria" },
            { word: "Prazo", similar: "Deadline" },
            { word: "Feedback", similar: "Avaliação" },
            { word: "Home Banking", similar: "Internet Banking" },
            { word: "Aumento", similar: "Promoção" }
        ],
        "Games e Cultura Geek": [
            { word: "Fortnite", similar: "Free Fire" },
            { word: "Minecraft", similar: "Roblox" },
            { word: "GTA", similar: "Red Dead Redemption" },
            { word: "League of Legends", similar: "Dota 2" },
            { word: "PlayStation 5", similar: "Xbox Series X" },
            { word: "Genshin Impact", similar: "Honkai Star Rail" },
            { word: "Valorant", similar: "CS2" },
            { word: "Pokémon", similar: "Digimon" },
            { word: "Mario", similar: "Sonic" },
            { word: "Zelda", similar: "Tomb Raider" },
            { word: "Among Us", similar: "Fall Guys" },
            { word: "Stranger Things", similar: "Dark" }
        ],
        "Esportes": [
            { word: "Futebol", similar: "Futsal" },
            { word: "Vôlei", similar: "Vôlei de Praia" },
            { word: "Corrida de Rua", similar: "Maratona" },
            { word: "Ciclismo", similar: "Spinning" },
            { word: "MMA", similar: "Boxe" },
            { word: "Basquete", similar: "Handebol" },
            { word: "Natação", similar: "Nado Sincronizado" },
            { word: "Tênis", similar: "Squash" },
            { word: "Skate", similar: "Longboard" },
            { word: "Jetski", similar: "Lancha Rápida" },
            { word: "Golfe", similar: "Boliche" },
            { word: "Yoga", similar: "Pilates" }
        ],
        "Corpo Humano e Treino": [
            { word: "Olho", similar: "Córnea" },
            { word: "Mão", similar: "Punho" },
            { word: "Coração", similar: "Pulmão" },
            { word: "Cabelo", similar: "Sobrancelha" },
            { word: "Nariz", similar: "Seios da Face" },
            { word: "Dente", similar: "Gengiva" },
            { word: "Dedo Indicador", similar: "Polegar" },
            { word: "Bíceps", similar: "Tríceps" },
            { word: "Costas", similar: "Lombar" },
            { word: "Panturrilha", similar: "Coxa" },
            { word: "Queixo", similar: "Mandíbula" },
            { word: "Pescoço", similar: "Nuca" },
            { word: "Tornozelo", similar: "Calcanhar" },
            { word: "Cotovelo", similar: "Ombro" },
            { word: "Estômago", similar: "Intestino" }
        ],
        "Transportes": [
            { word: "Moto", similar: "Scooter" },
            { word: "Carro Sedan", similar: "Carro Hatch" },
            { word: "Avião", similar: "Jato Particular" },
            { word: "Navio de Cruzeiro", similar: "Iate" },
            { word: "Trem", similar: "VLT" },
            { word: "Ônibus Urbano", similar: "Ônibus de Viagem" },
            { word: "Submarino", similar: "Cápsula de Mergulho" },
            { word: "Táxi", similar: "Mototáxi" },
            { word: "Foguete", similar: "Ônibus Espacial" },
            { word: "Teleférico", similar: "Bondinho" },
            { word: "Ambulância", similar: "Viatura Policial" },
            { word: "Caminhão Baú", similar: "Carreta" },
            { word: "Patinete Elétrico", similar: "Hoverboard" },
            { word: "Carro Elétrico", similar: "Carro Híbrido" }
        ],
        "Música e Entretenimento": [
            { word: "Show de Música", similar: "Festival" },
            { word: "Funk", similar: "Pagode" },
            { word: "Sertanejo", similar: "Forró" },
            { word: "Trap", similar: "Rap" },
            { word: "Karaokê", similar: "Playback" },
            { word: "Vinil", similar: "CD" },
            { word: "Rádio", similar: "Podcast" },
            { word: "Cinema", similar: "Teatro" },
            { word: "Filme", similar: "Série" },
            { word: "Novela", similar: "Reality Show" },
            { word: "Stand-up Comedy", similar: "Monólogo" },
            { word: "Show de Talentos", similar: "Reality Musical" }
        ]
    }
};